# Generated by Django 5.1.1 on 2024-10-15 17:00

import FWapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FWapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwarepackage',
            name='fw_package',
            field=models.FileField(upload_to=FWapp.models.firmware_upload_path),
        ),
    ]
